# Generated by Django 4.1.1 on 2022-11-19 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_body_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_label',
            field=models.CharField(default="Getty's Blog", max_length=300),
        ),
    ]
