# Generated by Django 4.1.1 on 2022-11-22 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
