# Generated by Django 4.1.1 on 2022-11-24 04:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='article_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
