# Generated by Django 4.1.1 on 2022-11-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_post_article_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='article_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
