# Generated by Django 4.1.1 on 2022-11-29 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
