# Generated by Django 4.1.1 on 2022-12-01 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
